substitutions:
  _TF_VERSION: 1.9.8
steps:
  - name: hashicorp/terraform:$_TF_VERSION
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
  - name: hashicorp/terraform:$_TF_VERSION
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve 
options:
  logging: CLOUD_LOGGING_ONLY