name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'jeremyto-billing-management'
  PROJECT_NMR: 396112887841
  
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/${{env.PROJECT_NMR}}/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: 'github-wif@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          project_id: ${{env.PROJECT_ID}}

      - name: Build and push the Docker image
        run: |-
          echo $PROJECT_ID
